---
title: "Plots-RV-Community"
author: "Stephanie Goya"
date: "2023-10-12"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(phytools)
library(ape)
library(readr)
library(svglite)
library(plyr)
library(RColorBrewer)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(AMR) #g.test
library(car)#multivatiate regression model
library(jtools)#multivatiate regression model
library(interactions)#multivatiate regression model
library(tidyverse)#logistic regression
library(caret)#logistic regression
library(cowplot)
library(epitools) #odd ratio
```

Association of RT-qPCR RV Ct value with symptoms, age and Sex of the individuals:
```{r PCR data analysis: Ct value and symptomatology/age_group, echo=TRUE}
PCR_data_RV <- read_csv("PCR_Ct_symp_age_20240130.csv") 
PCR_data_RV$CollectionMonth <- as.factor(substr(PCR_data_RV$CollectionDate,1,7))
PCR_data_RV$Sex <- as.factor(PCR_data_RV$Sex)
PCR_data_RV$Symptoms <- as.factor(PCR_data_RV$Symptoms)
PCR_data_RV$AgeGroup <- as.factor(PCR_data_RV$AgeGroup)
PCR_data_RV$Age <- as.numeric(PCR_data_RV$Age)
PCR_data_RV$RV_Ct_value <- as.numeric(PCR_data_RV$RV_Ct_value)

#analysis Ct versus age:
PCR_data_RV %>% group_by(AgeGroup) %>% get_summary_stats(RV_Ct_value, type="mean_sd")
#plotting Ct vs age groups
ordered_age_groups  = factor(PCR_data_RV$AgeGroup, levels=c("less5", "5-17", "18-65", "more65"))
A1 <- ggplot(data = PCR_data_RV, mapping = aes(x=ordered_age_groups, y=RV_Ct_value, fill=ordered_age_groups)) + geom_violin() + geom_boxplot(width=.1, color="white") + geom_jitter(color="black", size=0.2, alpha=0.9) + guides(fill = FALSE) + theme_minimal() + ylab("Ct value") + xlab("Age groups")

#Kruskal test Ct vs age:
res.age.kruskal <- kruskal_test(PCR_data_RV, RV_Ct_value ~ AgeGroup)
res.age.kruskal
#calculate effect size
res.age.effsize <- PCR_data_RV %>% kruskal_effsize(RV_Ct_value ~ AgeGroup)
res.age.effsize #(0.01- < 0.06 (small effect), 0.06 - < 0.14 (moderate effect) and >= 0.14 (large effect))

#Wilcoxon’s test - pairwise comparisons between group:
pwc.Ct.age <- ungroup(PCR_data_RV) %>% wilcox_test(RV_Ct_value ~ AgeGroup, p.adjust.method = "bonferroni") 
pwc.Ct.age
#plotting results:
pwc.Ct.age <- pwc.Ct.age %>% add_xy_position(x = "AgeGroup")
ggboxplot(PCR_data_RV, x = "AgeGroup", y = "RV_Ct_value") +
    stat_pvalue_manual(pwc.Ct.age, hide.ns = TRUE) +
    labs(
        subtitle = get_test_label(res.age.kruskal, detailed = TRUE),
        caption = get_pwc_label(pwc.Ct.age)
    )

#analysis Ct versus symptomatic:
#summary of the dataframe:
PCR_data_RV.NA <- na.omit(PCR_data_RV)
PCR_data_RV.NA$Symptoms <- factor(PCR_data_RV.NA$Symptoms, levels=c("Symptomatic", "Asymptomatic"))

ggboxplot(PCR_data_RV.NA, x="Symptoms", y="RV_Ct_value")
B1 <- ggplot(data = PCR_data_RV.NA, mapping = aes(x=Symptoms, y=RV_Ct_value, fill=Symptoms)) + geom_violin() + geom_boxplot(width=.1, color="white") + geom_jitter(color="black", size=0.2, alpha=0.9) + guides(fill = FALSE) + theme_minimal() + theme(axis.title.x=element_blank()) + ylab("Ct value")

#Kruskal test
res.sym.kruskal <- kruskal_test(PCR_data_RV.NA, RV_Ct_value ~ Symptoms)
res.sym.kruskal
#calculate effect size
res.sym.effsize <- PCR_data_RV.NA %>% kruskal_effsize(RV_Ct_value ~ Symptoms)
res.sym.effsize #(0.01- < 0.06 (small effect), 0.06 - < 0.14 (moderate effect) and >= 0.14 (large effect))

#Wilcoxon’s test to calculate pairwise comparisons between group levels with corrections for multiple testing:
pwc.ct <- PCR_data_RV.NA %>% 
  wilcox_test(RV_Ct_value ~ Symptoms, p.adjust.method = "bonferroni") 
pwc.ct

#visualization: box plots with p-values:
pwc.ct <- pwc.ct %>% add_xy_position(x = "Symptoms")
ggboxplot(PCR_data_RV.NA, x = "Symptoms", y = "RV_Ct_value") +
  stat_pvalue_manual(pwc.ct, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(res.sym.kruskal, detailed = TRUE),
    caption = get_pwc_label(pwc.ct)
    )

#Age versus symptoms
PCR_data_RV.NA %>% group_by(Symptoms) %>%
          get_summary_stats(Age, type="mean_sd")
ggboxplot(PCR_data_RV.NA, x="Symptoms", y="Age")
C1 <-ggplot(data = PCR_data_RV.NA, mapping = aes(x=Symptoms, y=Age, fill=Symptoms)) + geom_violin() + geom_boxplot(width=.1, color="white") + geom_jitter(color="black", size=0.2, alpha=0.9) + guides(fill = FALSE) + theme_minimal() + theme(axis.title.x=element_blank()) + ylab("Age")

#Kruskal test
res.ageSYM.kruskal <- kruskal_test(PCR_data_RV.NA, Age ~ Symptoms)
res.ageSYM.kruskal

#multivariate multiple regression model to study Ct, age and symptomatic
lm1 <- lm(RV_Ct_value~Symptoms+Age, data=PCR_data_RV.NA)
Anova(lm1)
#plot the model
avPlots(lm1)
#identify the formula:
summ(lm1, confint=TRUE, digits=3) #in this case the formula is: Ct= 27.892 + 0.018 x age - 2.715 x symptomatic (0=asymptomatic, 1=symptomatic: categorical variables are choose as baseline depending on alphabetical order)
#plot
interact_plot(lm1, pred=Age, modx=Symptoms, plot.points=TRUE, point.alpha=0.1, interval = TRUE, int.type = "confidence", int.width = .95) + ylab("Ct value")
D1 <- interact_plot(lm1, pred=Age, modx=Symptoms, plot.points=TRUE, point.alpha=0.1, interval = TRUE, int.type = "confidence", int.width = .95) + ylab("Ct value") + theme(legend.position = "none")

#verify normality of residuals
qqnorm(lm1$residuals)
qqline(lm1$residuals)

#save the plot:
plot_grid(A1, B1, C1, D1, labels = c('A', 'B', 'C', 'D'), align = "h")

```

RV seasonality plots with the Washington State genomes:
```{r RV seasonality, echo=TRUE}
#Loading the dataframe:
season_data_RV <- read_csv("RV-dataframe_20240130.csv") 
season_data_RV$CollectionMonth<- as.factor(substr(season_data_RV$CollectionDate,1,7))
season_data_RV$Genotype <- as.factor(season_data_RV$Genotype)
season_data_RV$Sex <- as.factor(season_data_RV$Sex)
season_data_RV$RVSpecie <- as.factor(season_data_RV$RVSpecie)
season_data_RV$Clinica <- as.factor(season_data_RV$Clinica)
season_data_RV$StudyPeriod <- as.factor(season_data_RV$StudyPeriod)
season_data_RV$AgeGroup <- as.factor(season_data_RV$AgeGroup)
season_data_RV$Age <- as.numeric(season_data_RV$Age)
season_data_RV$RV_Ct_value <- as.numeric(season_data_RV$RV_Ct_value)
season_data_RV$ZipCode <- as.factor(season_data_RV$ZipCode)

# ----->Bubble chart of seasonality of RV genotypes of all the species together. It is needed an Excel file containing a column for the sequence name and a column for the genotype:
condensed_season_data_RV <- ddply(season_data_RV,.(Genotype,CollectionMonth),nrow)

ggplot(condensed_season_data_RV, aes(x= factor(CollectionMonth), y=Genotype, size=V1)) + geom_point(alpha=0.5) + scale_y_discrete(limits=rev(c("A1B", "A2", "A7", "A9", "A11", "A12", "A13", "A16", "A18", "A20", "A21", "A22", "A23", "A24", "A25", "A28", "A29", "A30", "A31", "A32", "A33", "A34", "A38", "A39", "A45", "A46", "A47", "A49", "A53", "A54", "A58", "A59", "A60", "A61", "A62", "A63", "A64", "A66", "A67", "A68", "A73", "A78", "A80", "A85", "A94", "A101", "A105","A111" ,"B3", "B4", "B6", "B14", "B27", "B42", "B48", "B70", "B72", "B83", "B91", "B92", "B100", "B101", "B107", "C1", "C2", "C3", "C4", "C6", "C7", "C8", "C9", "C11", "C13", "C15", "C16", "C17", "C18", "C19", "C20", "C21", "C23", "C25", "C26", "C27", "C28", "C29", "C31", "C33", "C34", "C35", "C36", "C40", "C42", "C43", "C44", "C46", "C53", "C55", "C56"))) + xlab("Collection Date") + theme(axis.text.x = element_text(angle = 45, hjust = 1))


# ----->Barplot of the seasonality of RV species by month of sample collection. 
n <- length(unique(season_data_RV$RVSpecie))
qual_col_pals = brewer.pal.info[brewer.pal.info$category== 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

A2 <- ggplot(season_data_RV, aes(x=CollectionMonth, fill=RVSpecie)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.title.x=element_blank()) + labs(y="Proportion", fill = "Species") + scale_fill_manual(values = sample(col_vector, n))
A2

# ----->Barplot of the seasonality of RV-A genotypes by month of sample collection. 
season_data_RVA <- subset(season_data_RV, season_data_RV$RVSpecie=="A")
nA <- length(unique(season_data_RVA$Genotype))
qual_col_pals = brewer.pal.info[brewer.pal.info$category== 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

B2 <- ggplot(season_data_RVA, aes(x=CollectionMonth, fill=Genotype)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.title.x=element_blank()) + labs(y="Proportion", fill = "RV-A Genotype") + scale_fill_manual(values = sample(col_vector, nA), breaks = c("A1B", "A2", "A7", "A9", "A11", "A12", "A13", "A16", "A18", "A20", "A21", "A22", "A23", "A24", "A25", "A28", "A29", "A30", "A31", "A32", "A33", "A34", "A38", "A39", "A45", "A46", "A47", "A49", "A53", "A54", "A58", "A59", "A60", "A61", "A62", "A63", "A64", "A66", "A67", "A68", "A73", "A78", "A80", "A85", "A94", "A101", "A105", "A111"))
B2


# ----->Barplot of the seasonality of RV-B genotypes by month of sample collection. 
season_data_RVB <- subset(season_data_RV, season_data_RV$RVSpecie=="B")
nB <- length(unique(season_data_RVB$Genotype))
qual_col_pals = brewer.pal.info[brewer.pal.info$category== 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

C2 <- ggplot(season_data_RVB, aes(x=CollectionMonth, fill=Genotype)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.title.x=element_blank()) + labs(y="Proportion", fill = "RV-B Genotype") + scale_fill_manual(values = sample(col_vector, nB), breaks = c("B3", "B4", "B6", "B14", "B27", "B42", "B48", "B70", "B72", "B83", "B91", "B92", "B100", "B101", "B107"))
C2

# ----->Barplot of the seasonality of RV-C genotypes by month of sample collection. 
season_data_RVC <- subset(season_data_RV, season_data_RV$RVSpecie=="C")
nC <- length(unique(season_data_RVC$Genotype))
qual_col_pals = brewer.pal.info[brewer.pal.info$category== 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

D2 <- ggplot(season_data_RVC, aes(x=CollectionMonth, fill=Genotype)) + geom_bar(position = "fill") + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.title.x=element_blank()) + labs(y="Proportion", fill = "RV-C Genotype") + scale_fill_manual(values = sample(col_vector, nC), breaks = c("C1", "C2", "C3", "C4", "C6", "C7", "C8", "C9", "C11", "C13", "C15", "C16", "C17", "C18", "C19", "C20", "C21", "C23", "C25", "C26", "C27", "C28", "C29", "C31", "C33", "C34", "C35", "C36", "C40", "C42", "C43", "C44", "C46", "C53", "C55", "C56")) 
D2

```

Assocaition of RV species and genotypes with with clinical and epidemiological characteristics:
```{r, plots to evaluate the associacion of RV with clinical and epidemiological charactersitics, echo=TRUE}
#RV species versus individuals age
ggplot(season_data_RV, aes(x=RVSpecie, y=Age, fill=RVSpecie)) + geom_violin(width=1) + geom_boxplot(width=0.1, color="white", alpha=0.2) + geom_jitter(color="black", size=0.4, alpha=0.9) + theme_minimal()

#RV genotypes within RV species versus individuals age
season_data_RVA <- subset(season_data_RV, subset = RVSpecie == "A")
season_data_RVB <- subset(season_data_RV, subset = RVSpecie == "B")
season_data_RVC <- subset(season_data_RV, subset = RVSpecie == "C")

ggplot(season_data_RVA, aes(x=Genotype, y=Age)) + geom_violin(width=1) + geom_boxplot(width=0.1, color="black", alpha=0.2) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplot(season_data_RVB, aes(x=Genotype, y=Age)) + geom_violin(width=1) + geom_boxplot(width=0.1, color="black", alpha=0.2) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplot(season_data_RVC, aes(x=Genotype, y=Age)) + geom_violin(width=1) + geom_boxplot(width=0.1, color="black", alpha=0.2) + theme(axis.text.x = element_text(angle = 45, hjust = 1))


#Age Group and Sex by RV species
df_clinica <- season_data_RV[!is.na(season_data_RV$Age),]
ggplot(df_clinica, aes(x=RVSpecie, fill=AgeGroup)) + geom_bar(position = "dodge") 
ggplot(df_clinica, aes(x=AgeGroup, fill=RVSpecie)) + geom_bar(position = "fill") + scale_x_discrete(limits = c("less5", "5-17", "18-65", "more65"))
ggplot(df_clinica, aes(x=RVSpecie, fill=Sex)) + geom_bar(position = "dodge")
#statistical test
  df_clinica_Sex.spe <- as.matrix(table(df_clinica$RVSpecie, df_clinica$Sex))  
  g.test(df_clinica_Sex.spe)
  df_clinica_age.spe <- as.matrix(table(df_clinica$RVSpecie, df_clinica$AgeGroup))  
  g.test(df_clinica_age.spe)

fisher.test(df_clinica$RVSpecie, df_clinica$AgeGroup,simulate.p.value = TRUE)
#pairwise comparison in <5years old
AB_less5 <-matrix(c(31,148+69+10,1,42+16+6),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "B"), AgeGroup = c("less5", "above5"))) #RV-A vs RV-B
oddsratio.fisher(AB_less5)

AC_less5 <- matrix(c(44,106+41+12,31,148+69+10),nrow = 2, ncol = 2, dimnames=list(RV= c("C", "A"), AgeGroup = c("less5", "above5"))) #RV-A vs RV-C
oddsratio.fisher(AC_less5)

BC_less5 <- matrix(c(44,106+41+12,1,42+16+6),nrow = 2, ncol = 2, dimnames=list(RV= c("C", "B"), AgeGroup = c("less5", "above5"))) #RV-B vs RV-C
oddsratio.fisher(BC_less5)

#pairwise comparison in 5-17 years old
AB_517 <-matrix(c(69,148+31+10,16,42+1+6),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "B"), AgeGroup = c("5-17", "no5-17"))) #RV-A vs RV-B
oddsratio.fisher(AB_517)

AC_517 <- matrix(c(69,148+31+10,41,106+44+12),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "C"), AgeGroup = c("5-17", "no5-17"))) #RV-A vs RV-C
oddsratio.fisher(AC_517)

BC_517 <- matrix(c(16,42+1+6,41,106+44+12),nrow = 2, ncol = 2, dimnames=list(RV= c("B", "C"), AgeGroup = c("5-17", "no5-17"))) #RV-B vs RV-C
oddsratio.fisher(BC_517)

#pairwise comparison in 18-65 years old
AB_1865 <-matrix(c(148,69+31+10,42,16+1+6),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "B"), AgeGroup = c("18-65", "no18-65"))) #RV-A vs RV-B
oddsratio.fisher(AB_1865)

AC_1865 <- matrix(c(148,69+31+10,106,41+44+12),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "C"), AgeGroup = c("18-65", "no18-65"))) #RV-A vs RV-C
oddsratio.fisher(AC_1865)

BC_1865 <- matrix(c(42,16+1+6,106,41+44+12),nrow = 2, ncol = 2, dimnames=list(RV= c("B", "C"), AgeGroup = c("18-65", "no18-65"))) #RV-B vs RV-C
oddsratio.fisher(BC_1865)

#pairwise comparison in more65 years old
AB_more65 <-matrix(c(10,69+31+148,6,16+1+42),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "B"), AgeGroup = c("more65", "below65"))) #RV-A vs RV-B
oddsratio.fisher(AB_more65)

AC_more65 <- matrix(c(10,69+31+148,12,41+44+106),nrow = 2, ncol = 2, dimnames=list(RV= c("A", "C"), AgeGroup = c("more65", "below65"))) #RV-A vs RV-C
oddsratio.fisher(AC_more65)

BC_more65 <- matrix(c(6,16+1+42,12,41+44+106),nrow = 2, ncol = 2, dimnames=list(RV= c("B", "C"), AgeGroup = c("more65", "below65"))) #RV-B vs RV-C
oddsratio.fisher(BC_more65)

#Symptoms versus RV species
df_clinica.SYM <- df_clinica[!is.na(df_clinica$Clinica),]
ggplot(df_clinica.SYM, aes(x=Clinica, fill=RVSpecie)) + geom_bar(position = "dodge")
#statistical test
  df_clinica_sym.spe <- as.matrix(table(df_clinica.SYM$RVSpecie, df_clinica.SYM$Clinica))  
  g.test(df_clinica_sym.spe)

#Odd ratio for Symptoms and Ct<25
df_clinica.SYM$Ct25 <- ifelse(df_clinica.SYM$RV_Ct_value<25, "below25", "above25")
oddsratio.wald(table(df_clinica.SYM$Clinica, df_clinica.SYM$Ct25))
oddsratio.fisher(table(df_clinica.SYM$Clinica, df_clinica.SYM$Ct25))

#Symptoms by age group per RV species
df_clinica.SYMA <- subset(df_clinica.SYM, subset = RVSpecie == "A")
df_clinica.SYMB <- subset(df_clinica.SYM, subset = RVSpecie == "B")
df_clinica.SYMC <- subset(df_clinica.SYM, subset = RVSpecie == "C")

ggplot(df_clinica.SYMA, aes(x=AgeGroup, fill=Clinica)) + geom_bar(position = "fill") + scale_x_discrete(limits = c("less5", "5-17", "18-65", "more65"))

    df_clinica.SYMA_sym.age <- as.matrix(table(df_clinica.SYMA$Clinica, df_clinica.SYMA$AgeGroup))  
    g.test(df_clinica.SYMA_sym.age)

ggplot(df_clinica.SYMB, aes(x=AgeGroup, fill=Clinica)) + geom_bar(position = "fill") + scale_x_discrete(limits = c("less5", "5-17", "18-65", "more65"))

    df_clinica.SYMB_sym.age <- as.matrix(table(df_clinica.SYMB$Clinica, df_clinica.SYMB$AgeGroup))  
    g.test(df_clinica.SYMB_sym.age)
  
ggplot(df_clinica.SYMC, aes(x=AgeGroup, fill=Clinica)) + geom_bar(position = "fill") + scale_x_discrete(limits = c("less5", "5-17", "18-65", "more65"))

    df_clinica.SYMC_sym.age <- as.matrix(table(df_clinica.SYMC$Clinica, df_clinica.SYMC$AgeGroup))  
    g.test(df_clinica.SYMC_sym.age)

#logistic regressions to evaluate association with geographic location and individuals age:
season_data_RV %>% group_by(ZipCode) %>%
get_summary_stats(Age, type="mean_sd") %>% print(n = 25)

#plotting
season_data_RV_clean <- season_data_RV[!is.na(season_data_RV$ZipCode),]

ggplot(season_data_RV_clean, aes(x=ZipCode, y=Age)) + geom_violin(width=1) + geom_boxplot(width=0.1, color="black", alpha=0.2) + theme(axis.text.x = element_text(angle = 45, hjust = 1))

#if leaving zip code with more than 5 cases reported:
season_data_RV.5 <- season_data_RV %>%
  group_by(ZipCode) %>%
  filter(n() > 5) %>%
  na.omit(season_data_RV.5$ZipCode)

ggplot(season_data_RV.5, aes(x=ZipCode, y=Age)) +  geom_boxplot(width=0.1, color="black", alpha=0.2) + theme(axis.text.x = element_text(angle = 45, hjust = 1))

#multivariate multiple regression model to study Ct, symptoms and RV SPECIES (using data frame of sequenced samples):
season_data_RV_clean <- season_data_RV[!is.na(season_data_RV$Clinica),]

lm_reg1 <- lm(RV_Ct_value~Clinica+RVSpecie, season_data_RV_clean)
Anova(lm_reg1)
#plot the model
avPlots(lm_reg1)
#identify the formula:
summ(lm_reg1, confint=TRUE, digits=3) #in this case the formula is: Ct= 27.892 + 0.018 x age - 2.715 x symptomatic (0=asymptomatic, 1=symptomatic: categorical variables are choose as baseline depending on alphabetical order)

#verify normality of residuals
qqnorm(lm_reg1$residuals)
qqline(lm_reg1$residuals)

#Ct value and the genotypes (with more than 5 cases detected):
season_data_RV_CT.5 <- season_data_RV %>% group_by(Genotype) %>% filter(n() > 5) %>% filter(RV_Ct_value!="NA")
season_data_RV_CT.5$Genotype<- as.factor(season_data_RV_CT.5$Genotype)
#Kruskal test
res.gen.ct.kruskal <- kruskal_test(season_data_RV_CT.5, season_data_RV_CT.5$RV_Ct_value ~ season_data_RV_CT.5$Genotype)
res.gen.ct.kruskal

#calculate effect size
res.gen.ct.effsize <- season_data_RV %>% kruskal_effsize(RV_Ct_value ~ Genotype)
res.gen.ct.effsize #(0.01- < 0.06 (small effect), 0.06 - < 0.14 (moderate effect) and >= 0.14 (large effect))

#All genotypes versus Ct value
ggboxplot(season_data_RV, x = "Genotype", y = "RV_Ct_value") + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))

#Genotypes with more than 5 cases detected, versus Ct value
ggboxplot(season_data_RV_CT.5, x = "Genotype", y = "RV_Ct_value") + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))

```





